application: #application
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

#- url: /_ah/spi/.*
#  script: start.APPLICATION
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION

# Third party libraries that are included in the App Engine SDK must be listed
# here if you want to use them. See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK. Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
# Note that dependencies must be located in your project directory - packages
# installed in the Python environment are not loaded by the App Engine
# development server or deployment tools.
# TODO: List any other App Engine SDK libs you may need here.
libraries:

# You must include the Endpoints library if you wish to serve an API.
- name: endpoints
  version: 1.0

# The pycrypto library is used for OAuth 2, and is also a requirement for
# APIs that wish to authenticate users.
- name: pycrypto
  version: latest
